### ISSUE TITLE
Buff paper -> boards

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/SeaBlock#15]
Needs to be done eventually. Consider if it could be done in a way that could be merged back into Angel's.

**Comment by KiwiHawk** [comment]
Paper 3 creates sodium carbonate apparently. Which has no real demand

**Comment by craig-johnston** [comment]
The sodium carbonate is great in paper 3 because you put in a loop to get back to sodium hydroxide.

I just looked at this recently and I think the problems are (considering paper and pulp recipes separately):
* Paper to board recipe
* Sheer number of machines
* Progression isn't buffed sufficiently, so no reason to go past paper 1
* paper-2, sodium hypochlorite output is non-voidable, unhelpful
* paper-2, sodium hydroxide (and chlorine) input is really hard without access to sodium processing (blue science), also requires tones of saline water which means a compact build is locked behind salination plants (requires advanced (red) circuits up and running)
* paper-3 is a well balanced recipe, but throughput is a problem . It just requires too many machines: 1.1 board/sec per advanced chem plant
* pulp-2, requires too much sulphur for when it's unlocked. The sodium sulphate output can't be effectively used until sodium processing is unlocked, so it just drains sulphur. However it's reasonable once that's unlocked (it becomes positive sulphur and sodium hydroxide). This is OK, as you could stick with the pulp-1 recipe until that's done, but likely going to skip right over it for pulp-3 unless pulp-3 is much deeper into the tech tree

So here's some suggestions for fixes
* Add electronic assembler for paper -> board recipe (early game that doubles the speed)
* Reduce paper -> board recipe time (at least halve)
* OR consider adding new "bulk" paper -> board recipes to paper 2, 3 so that it scales with tech level (e.g. extra inputs for "drying" or different machines but large input/output amounts)
* Increase the amount of paper created in paper-2 and throughput, remove waste product, reduce NaOH input. Recipe becomes: 3 pulp, 1 NaOH, 30 Cl -> 9 paper
* Increase amount of paper created in paper-3 and throughput by reducing recipe time. 2 pulp, 2 NaOH, 60 H2, 40 SO2, 100 H20 -> 10 paper, 2 Na2CO3, 100 SWW, change recipe time from 4s -> 1s
* Allow prod modules??
* Move paper 3 into pink or purple science

And the intent would be that paper is used for all boards, so need to remove wood->board recipes

For some other ideas:
* Consider introducing paper to phenolic board, etc. directly instead of via board as a way of scaling the paper->board recipe better (e.g. unlocks that in paper-3, now can produce phenolic boards at double the rate with same level machines)
* Have paper-2 produce CWW or a useful by product (but what?)

**Comment by KiwiHawk** [comment]
From discord: "A thought occurred to me. Sodium hypochlorite decomposes when heated to sodium chloride with the release of oxygen. Maybe it makes sense to add something like 5 NaOCl --> 5 NaCl + 50 O2 as an early way to recycle by-products of kraft paper for the red level of sciences, say chlorine recycling 2"

**Comment by jodokus31** [comment]
I want to add, that arboretums are obscenely efficient in producing wooden boards, even at T1. Maybe it should scale a bit harder, that T1 a lot less efficient, but T3 is untouched.

**Comment by atburghardt** [comment]
I have another proposal for this issue:
https://github.com/Arch666Angel/mods/issues/803
Please check in Angels, pullrequest in draft at the moment.
Happy for suggestions, if this approach is something you like.

**Comment by KiwiHawk** [comment]
Closing as this has been done in Angel's.
